---
# Application configuration

# Environment settings
node_env: development
port: 4000

# OCPI Configuration
ocpi:
  url: ${OCPI_URL}
  auth_key: ${OCPI_AUTH_KEY}

# Beckn Protocol Configuration
beckn:
  version: "2.0" # Supported versions: "1.0", "2.0"
  bpp_id: ${BPP_ID}
  bpp_uri: ${BPP_URI}
  protocol_server_url: ${PROTOCOL_SERVER_URL}

# Application specific configuration
app:
  discovery:
    default_radius_meters: 5000  # 5km default radius
    standard_session_kwh: 1      # Assumed standard session of 1 kWh
    share_location_details: false  # Whether to share location details on discovery
  initialization:
    refresh_ocpi_cache_on_startup: false
    use_cache: false
  defaults:
    item_name: 'EV Charger'
  cancellation_terms:
    - fulfillment_state: confirmed
      cancellation_fee:
        percentage: 30

cache:
  host: ${CACHE_HOST}
  port: ${CACHE_PORT}
  password: ${REDIS_PASSWORD}
  ttl_seconds: ${CACHE_TTL_SECONDS}

clickhouse: # for logging
  host: ${CLICKHOUSE_HOST}
  port: ${CLICKHOUSE_PORT}
  database: default
  username: default
  password: ${CLICKHOUSE_PASSWORD}
  log_table: app_logs
